console.log('▕▔▔▔▔▔▔▔▔▔▔▔╲┈┈┈');
console.log('▕╮╭┻┻╮╭┻┻╮╭▕╮╲┈┈');
console.log('▕╯┃╭╮┃┃╭╮┃╰▕╯╭▏┈');
console.log('▕╭┻┻┻┛┗┻┻┛┈▕┈╰▏┈');
console.log('▕╰━━━┓┈┈┈╭╮▕╭╮▏┈');
console.log('▕╭╮╰┳┳┳┳╯╰╯▕╰╯▏┈');
console.log('▕╰╯┈┗┛┗┛┈╭╮▕╮┈▏┈');
console.log('cao');
console.log('Zdravo');
console.log('( ´ ▽ ` )ﾉ');
